In [10]:
import pandas as pd
import missingno as msnp
import re

In [19]:
df = pd.read_csv(r'/content/MinimumWageData.csv', encoding='ISO-8859-1')

In [20]:
df.tail()

,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
2857,2020,Virginia,7.25,7.25,7.25,7.25,7.25,7.25,258.66,7.25[c],7.25,7.25,7.25,7.25,[c]
2858,2020,Washington,13.50,13.50,7.25,7.25,13.50,13.50,258.66,13.5,13.50,13.50,13.50,13.50,NaN
2859,2020,West Virginia,8.75,8.75,7.25,7.25,8.75,8.75,258.66,8.75,8.75,8.75,8.75,8.75,NaN
2860,2020,Wisconsin,7.25,7.25,7.25,7.25,7.25,7.25,258.66,7.25,7.25,7.25,7.25,7.25,NaN
2861,2020,Wyoming,5.15,5.15,7.25,7.25,7.25,7.25,258.66,5.15,5.15,5.15,5.15,5.15,NaN

**Renaming the Dataset columns name**

In [21]:
df = df.set_axis(['Year', 'State', 'State_Minimum_Wage','State_Minimum_Wage_2020($)' ,'Federal_Minimum_Wage', 'Federal_Minimum_Wage_2020($)', 'Effective_Minimum_Wage' ,'Effective_Minimum_Wage_2020($)' ,'CPI_Avg' , 'Department_Of_Labor' ,'Department_Of_Labor_low_val' ,'Department_Of_Labor_low_val_2020($)' , 'Department_Of_Labor_high_val' ,'Department_Of_Labor_high_val_2020($)' ,'FootNote' ] ,axis = 1)

In [22]:
df

,Year,State,State_Minimum_Wage,State_Minimum_Wage_2020($),Federal_Minimum_Wage,Federal_Minimum_Wage_2020($),Effective_Minimum_Wage,Effective_Minimum_Wage_2020($),CPI_Avg,Department_Of_Labor,Department_Of_Labor_low_val,Department_Of_Labor_low_val_2020($),Department_Of_Labor_high_val,Department_Of_Labor_high_val_2020($),FootNote
0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.80,...,0.00000,0.00,0.00000,0.00,NaN
1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.80,2.1,2.10000,15.61,2.10000,15.61,NaN
2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.80,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91,(b)
3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.80,1.25/day(b),0.15625,1.16,0.15625,1.16,(b)
4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.80,1.65(b),1.65000,12.26,1.65000,12.26,(b)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,2020,Virginia,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25[c],7.25000,7.25,7.25000,7.25,[c]
2858,2020,Washington,13.50000,13.50,7.25,7.25,13.50,13.50,258.66,13.5,13.50000,13.50,13.50000,13.50,NaN
2859,2020,West Virginia,8.75000,8.75,7.25,7.25,8.75,8.75,258.66,8.75,8.75000,8.75,8.75000,8.75,NaN
2860,2020,Wisconsin,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25,7.25000,7.25,7.25000,7.25,NaN
2861,2020,Wyoming,5.15000,5.15,7.25,7.25,7.25,7.25,258.66,5.15,5.15000,5.15,5.15000,5.15,NaN

In [23]:
del df['FootNote']

In [24]:
df

,Year,State,State_Minimum_Wage,State_Minimum_Wage_2020($),Federal_Minimum_Wage,Federal_Minimum_Wage_2020($),Effective_Minimum_Wage,Effective_Minimum_Wage_2020($),CPI_Avg,Department_Of_Labor,Department_Of_Labor_low_val,Department_Of_Labor_low_val_2020($),Department_Of_Labor_high_val,Department_Of_Labor_high_val_2020($)
0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.80,...,0.00000,0.00,0.00000,0.00
1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.80,2.1,2.10000,15.61,2.10000,15.61
2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.80,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91
3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.80,1.25/day(b),0.15625,1.16,0.15625,1.16
4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.80,1.65(b),1.65000,12.26,1.65000,12.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,2020,Virginia,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25[c],7.25000,7.25,7.25000,7.25
2858,2020,Washington,13.50000,13.50,7.25,7.25,13.50,13.50,258.66,13.5,13.50000,13.50,13.50000,13.50
2859,2020,West Virginia,8.75000,8.75,7.25,7.25,8.75,8.75,258.66,8.75,8.75000,8.75,8.75000,8.75
2860,2020,Wisconsin,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25,7.25000,7.25,7.25000,7.25
2861,2020,Wyoming,5.15000,5.15,7.25,7.25,7.25,7.25,258.66,5.15,5.15000,5.15,5.15000,5.15

**Exploratory Data Analysis**

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Year                                  2862 non-null   int64
 1   State                                 2862 non-null   object
 2   State_Minimum_Wage                    2862 non-null   float64
 3   State_Minimum_Wage_2020($)            2862 non-null   float64
 4   Federal_Minimum_Wage                  2862 non-null   float64
 5   Federal_Minimum_Wage_2020($)          2862 non-null   float64
 6   Effective_Minimum_Wage                2862 non-null   float64
 7   Effective_Minimum_Wage_2020($)        2862 non-null   float64
 8   CPI_Avg                               2862 non-null   float64
 9   Department_Of_Labor                   2862 non-null   object
 10  Department_Of_Labor_low_val           2862 non-null   float64
 11  Department_Of_Labor_low_val_2020($)   2847 non-null   float64
 12  Department_Of_Labor_high_val          2862 non-null   float64
 13  Department_Of_Labor_high_val_2020($)  2847 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 313.2+ KB

In [26]:
df.describe()

,Year,State_Minimum_Wage,State_Minimum_Wage_2020($),Federal_Minimum_Wage,Federal_Minimum_Wage_2020($),Effective_Minimum_Wage,Effective_Minimum_Wage_2020($),CPI_Avg,Department_Of_Labor_low_val,Department_Of_Labor_low_val_2020($),Department_Of_Labor_high_val,Department_Of_Labor_high_val_2020($)
count,2862.000000,2862.000000,2862.000000,2862.000000,2862.000000,2862.000000,2862.000000,2862.000000,2862.000000,2847.000000,2862.000000,2847.000000
mean,1994.000000,3.754499,6.441635,4.355660,7.991887,4.624333,8.360758,145.417585,3.754499,6.475574,3.877663,6.719726
std,15.299732,2.804826,3.203165,1.959252,0.895547,2.324131,1.128870,69.361536,2.804826,3.177182,2.821064,3.172770
min,1968.000000,0.000000,0.000000,1.150000,6.420000,1.150000,6.420000,34.800000,0.000000,0.000000,0.000000,0.000000
25%,1981.000000,1.600000,5.352500,3.350000,7.340000,3.350000,7.610000,90.900000,1.600000,5.415000,1.600000,6.200000
50%,1994.000000,3.350000,7.400000,4.250000,7.900000,4.250000,8.170000,148.200000,3.350000,7.420000,3.350000,7.610000
75%,2007.000000,5.150000,8.450000,5.150000,8.390000,6.550000,8.980000,207.342000,5.150000,8.460000,5.825000,8.600000
max,2020.000000,14.000000,15.610000,7.250000,10.330000,14.000000,15.610000,258.660000,14.000000,15.610000,14.000000,15.610000

**Removing Special Characters**

In [101]:
df['Department_Of_Labor'] = df['Department_Of_Labor'].replace(special_characters,'')

In [102]:
df['Department_Of_Labor']

0         ...
1         2.1
2       26.40
3        1.25
4        1.65
        ...
2857     7.25
2858     13.5
2859     8.75
2860     7.25
2861     5.15
Name: Department_Of_Labor, Length: 2862, dtype: object

In [104]:
df.to_csv('updated_wage.csv')